# Generated by Django 4.0 on 2021-12-27 18:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип автомобиля: легковой, грузовой, лимузин')),
            ],
            options={
                'verbose_name': 'Тип автомобиля',
                'verbose_name_plural': 'Тип автомобиля',
            },
        ),
        migrations.CreateModel(
            name='RentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название прокатного сервиса')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес прокатного сервиса')),
            ],
            options={
                'verbose_name': 'Прокат',
                'verbose_name_plural': 'Прокаты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('second_name', models.TextField(max_length=200)),
                ('third_name', models.TextField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=200)),
                ('experience', models.IntegerField(verbose_name='Стаж, в целых годах')),
                ('drivers_license', models.IntegerField(verbose_name='Номер водительского удостоверения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('license_plate', models.CharField(max_length=50, verbose_name='Государственный номер')),
                ('daily_cost', models.FloatField(verbose_name='Посуточная стоимость аренды, в рублях')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_types', to='booking.cartype')),
                ('rental_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rental_services', to='booking.rentalservice')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_booking', models.DateField(verbose_name='Дата начала бронирования')),
                ('end_of_booking', models.DateField(verbose_name='Дата окончания бронирования')),
                ('request_status', models.CharField(choices=[('created', 'Создана'), ('in_progress', 'На рассмотрении'), ('approved', 'Бронирование подтверждено'), ('canceled', 'Отменено')], max_length=15, verbose_name='Статус заявки на бронирование')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_booking_request', to='booking.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_booking_request', to='booking.client')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
            },
        ),
    ]
