# Generated by Django 3.2.10 on 2021-12-27 19:21

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='drivers_license',
            field=models.IntegerField(null=True, verbose_name='Номер водительского удостоверения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='Стаж, в целых годах'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='third_name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
